Try to download libraries into /app/vendor/vips folder too

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -23,13 +23,23 @@ echo "Installing libvips" | arrow
 cd $BUILD_DIR
 
 output_dir="${BUILD_DIR}/vendor/vips"
+# Output library also to temp dir accordingly to pkg-config paths
+temp_app_dir="/app/vendor/vips"
 mkdir -p $output_dir
+mkdir -p $temp_app_dir
 
 echo "Downloading libvips and unpacking" | indent
 curl -s https://s3-eu-west-1.amazonaws.com/visup-misc/heroku-buildpack-vips/201402181300.tar.gz | tar xz -C $output_dir
 
 if [ $? != 0 ]; then
-  echo "Error downloading vips and unpacking" | indent
+  echo "Error downloading vips and unpacking to build dir" | indent
+  exit 1
+fi
+
+curl -s https://s3-eu-west-1.amazonaws.com/visup-misc/heroku-buildpack-vips/201402181300.tar.gz | tar xz -C $temp_app_dir
+
+if [ $? != 0 ]; then
+  echo "Error downloading vips and unpacking to app dir" | indent
   exit 1
 fi
 
@@ -40,10 +50,6 @@ echo "libvips installed" | indent
 echo "Creating new env var in $3" | indent
 
 echo "\$PKG_CONFIG_PATH:$BUILD_DIR/vendor/vips/lib/pkgconfig" > $3/PKG_CONFIG_PATH
-echo "\$LIBRARY_PATH:$BUILD_DIR/vendor/vips/lib" > $3/LIBRARY_PATH
-echo "\$LD_LIBRARY_PATH:$BUILD_DIR/vendor/vips/lib" > $3/LD_LIBRARY_PATH
-echo "\$CPATH:$BUILD_DIR/vendor/vips/include" > $3/CPATH
-echo "\$CPPPATH:$BUILD_DIR/vendor/vips/include" > $3/CPPPATH
 
 echo "Installing vips .profile.d files" | indent
 
